"""empty message

Revision ID: 268349bba21a
Revises: e3461de115ad
Create Date: 2026-02-01 13:42:29.120801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268349bba21a'
down_revision = 'e3461de115ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('client_pkey')),
    sa.UniqueConstraint('email', name=op.f('client_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('clients')
    # ### end Alembic commands ###
