"""Add placement to products

Revision ID: 42423ba3d0b2
Revises: 135be222ea48
Create Date: 2026-02-24 16:34:17.643423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42423ba3d0b2'
down_revision = '135be222ea48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('placement')

    # ### end Alembic commands ###
