"""Add photo_url column

Revision ID: 83268ec52540
Revises: 
Create Date: 2026-02-12 21:59:54.487413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83268ec52540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
