"""empty message

Revision ID: 87904f2765e4
Revises: 
Create Date: 2026-02-16 19:16:15.215702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87904f2765e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column(
            'start_date',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using="start_date::date"
        )

        batch_op.alter_column(
            'end_date',
            existing_type=sa.VARCHAR(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using="end_date::date"
        )

        batch_op.alter_column(
            'status',
            existing_type=sa.BOOLEAN(),
            type_=sa.String(length=20),
            nullable=False,
            postgresql_using="status::text"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.String(length=20),
                              type_=sa.BOOLEAN(),
                              nullable=True)
        batch_op.alter_column('end_date',
                              existing_type=sa.Date(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)
        batch_op.alter_column('start_date',
                              existing_type=sa.Date(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)

    # ### end Alembic commands ###
