"""Add messages table

Revision ID: 88915c3717fd
Revises: 1a22cfc2b59b
Create Date: 2026-02-13 20:39:48.855935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88915c3717fd'
down_revision = '1a22cfc2b59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sender_role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('receiver_role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('content', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('content')
        batch_op.drop_column('receiver_role')
        batch_op.drop_column('sender_role')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
